spring.datasource.url=jdbc:postgresql://localhost:5433/illegal_ecommerce
spring.datasource.username=illegal
spring.datasource.password=IllegalDev2024
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.validate-migration-naming=true

jwt.secret=3nGk9r2+4Pz1sKQxF6v8UjQwH2b7YtVx5fK0dL1zM0Q=
jwt.expiration=86400000

